export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const NEW_POST = 'NEW_POST';
export const FETCH_ONE ='FETCH_ONE';
export const UPDATE_POST = 'UPDATE_POST';
export const NEW_IMG = 'NEW_IMG';
export const FETCH_IMG = 'FETCH_IMG';
export const ALL_IMG = 'ALL_IMG';
export const FETCH_ACCENT = "FETCH_ACCENT";
// export const NEW_POSTIMG = 'NEW_POSTIMG';
